version: '3.4'
services:
    db:
        image: gustavostingelin/mysql-rest-with-springboot
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build: 
            context: ./Database
            dockerfile: Dockerfile
        environment: 
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: rest_with_spring_boot
        ports: 
            - "3306:3306"
        networks: 
            - springboot-network
    api:
        image: gustavostingelin/api-rest-with-springboot
        restart: always
        build: ./API
        working_dir: /API
        environment: 
            TZ: America/Sao_Paulo
            SPRING_BOOT_ENVIROMENT: Production
        volumes: 
            - ./API:/API
            - ~/.m2:/root/.m2
        ports: 
            - "8080:8080"
        command: mvn clean spring-boot:run
        links: 
            - db
        depends_on: 
            - db
        networks: 
            - springboot-network
networks:
    springboot-network:
        driver: bridge